# Generated by Django 5.0.1 on 2024-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_departments_group_semester_session_shift_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Sub_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Sub_id',
            field=models.ManyToManyField(related_name='subject_of_teachers', to='baseapp.subjects'),
        ),
    ]
