# Generated by Django 5.0.2 on 2024-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_subjects_dep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='principal_aproval',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
