# Generated by Django 5.0.2 on 2024-02-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_teacher_principal_aproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_group_for_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.departments')),
                ('Sem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.semester')),
                ('Subjects_groups', models.ManyToManyField(related_name='Siubjects', to='baseapp.subjects')),
            ],
        ),
    ]
