# Generated by Django 5.0.2 on 2024-02-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_subject_group_for_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='Semester_ID',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], max_length=50),
        ),
    ]
