# Generated by Django 5.0.2 on 2024-02-27 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_semester_semester_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=50)),
                ('father_ocupation', models.CharField(max_length=50)),
                ('father_mobile', models.CharField(max_length=11)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_ocupation', models.CharField(max_length=50)),
                ('mother_mobile', models.CharField(max_length=11)),
                ('mother_email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('permenent_address', models.TextField()),
                ('Examination', models.CharField(max_length=100)),
                ('examr_roll', models.CharField(max_length=25)),
                ('exam_year', models.CharField(max_length=4)),
                ('Examresult', models.CharField(max_length=5)),
                ('aproval_status', models.CharField(default='0', max_length=1)),
                ('Dep_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.departments')),
                ('Sem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.semester')),
                ('Session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.session')),
                ('Subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.subject_group_for_student')),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.group')),
                ('shift_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.shift')),
            ],
        ),
    ]
