# Generated by Django 5.0.2 on 2024-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_student_father_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Principal'), (2, 'HOD'), (3, 'Instractor'), (4, 'STUDENT'), (5, 'Neeer_Manager')], max_length=50),
        ),
    ]
