# Generated by Django 5.0.2 on 2024-03-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_attendanceobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceobject',
            name='Shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_attendance', to='baseapp.shift'),
        ),
    ]
