# Generated by Django 5.0.3 on 2024-03-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_subjects_creadite'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='PC',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='TC',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='Creadite',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
