# Generated by Django 5.0.2 on 2024-03-06 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_subjects_pc_subjects_tc_alter_subjects_creadite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_for_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_start', models.DateField()),
                ('Leave_end', models.DateField()),
                ('message', models.TextField()),
                ('status', models.CharField(default='0', max_length=1)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aproved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aproved_byApply_for_leave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
