# Generated by Django 5.0.2 on 2024-03-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_apply_for_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publised_status', models.CharField(default='0', max_length=1)),
                ('Credit', models.FloatField()),
                ('TC_Mark', models.FloatField()),
                ('PC_Mark', models.FloatField()),
                ('Total_TCPC_Mark', models.FloatField()),
                ('Total_Mark_of_Subject', models.FloatField()),
                ('Persentice', models.FloatField()),
                ('Subjec_GPA', models.FloatField()),
                ('Subject_Grade', models.CharField(max_length=5)),
                ('Pass_or_Fail', models.CharField(default='1', max_length=1)),
                ('Sem_Mark_helper', models.FloatField()),
                ('Semesters_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_mark', to='baseapp.semester')),
                ('Student_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_mark', to='baseapp.student')),
                ('Subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_mark', to='baseapp.subjects')),
            ],
        ),
    ]
