# Generated by Django 5.0.2 on 2024-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0016_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_mark',
            name='Credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='PC_Mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Pass_or_Fail',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Persentice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Sem_Mark_helper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Subjec_GPA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Subject_Grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='TC_Mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Total_Mark_of_Subject',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='Total_TCPC_Mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='publised_status',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
    ]
