# Generated by Django 5.0.2 on 2024-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0017_alter_student_mark_credit_alter_student_mark_pc_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_mark',
            name='Credit',
            field=models.FloatField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='PC_Mark',
            field=models.FloatField(blank=True, default=0.01, null=True),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='TC_Mark',
            field=models.FloatField(blank=True, default=0.01, null=True),
        ),
    ]
