# Generated by Django 5.0.2 on 2024-03-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0018_alter_student_mark_credit_alter_student_mark_pc_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_disable_or_not',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
