# Generated by Django 5.0.2 on 2024-03-10 03:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0019_student_student_disable_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='Semester_ID',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester'), ('9', 'Nine Semester')], max_length=50),
        ),
        migrations.CreateModel(
            name='message_model_for_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_model', to=settings.AUTH_USER_MODEL)),
                ('to_reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_model2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
