# Generated by Django 5.0.2 on 2024-03-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0021_main_bank_savingsaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_model_for_user',
            name='reciver_seen_status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='message_model_for_user',
            name='sender_seen_status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
