# Generated by Django 5.0.2 on 2024-02-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neer_page_caroules',
            name='Slide_discription',
            field=models.TextField(),
        ),
    ]
