# Generated by Django 5.0.2 on 2024-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0005_neerapp_coursess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thakurgaon_Polytechnic_Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collage_Name', models.CharField(max_length=50)),
                ('Collage_Image', models.ImageField(upload_to='collage_images')),
                ('Collge_Discrition', models.TextField()),
            ],
        ),
    ]
