# Generated by Django 5.0.2 on 2024-02-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0006_thakurgaon_polytechnic_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_of_TPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mission_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vission_of_TPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vission_text', models.TextField()),
            ],
        ),
    ]
