# Generated by Django 5.0.2 on 2024-02-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0007_mission_of_tpi_vission_of_tpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_title', models.CharField(max_length=50)),
                ('img_type', models.CharField(max_length=1)),
                ('Image', models.ImageField(upload_to='images_gallary')),
            ],
        ),
    ]
