# Generated by Django 5.0.2 on 2024-02-24 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0010_alter_block_post_of_tip_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_on_block_post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reply_of_comments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
