# Generated by Django 5.0.2 on 2024-02-25 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0012_notice_of_tpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_of_tpi',
            name='Expird_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
