# Generated by Django 5.0.2 on 2024-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0013_notice_of_tpi_expird_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_of_tpi',
            name='Expird_date',
            field=models.DateField(),
        ),
    ]
