# Generated by Django 5.0.2 on 2024-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0014_alter_notice_of_tpi_expird_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_of_tpi',
            name='aproval_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
