# Generated by Django 5.0.2 on 2024-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0015_notice_of_tpi_aproval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contuct_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField()),
                ('tip_email_1', models.EmailField(max_length=254)),
                ('tip_email_2', models.EmailField(max_length=254)),
                ('tip_phone_1', models.CharField(max_length=14)),
                ('tip_phone_2', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Public_masseges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Massages_sender_name', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(max_length=254)),
                ('messagess_subject', models.CharField(max_length=150)),
                ('messages_text', models.TextField()),
            ],
        ),
    ]
