# Generated by Django 5.0.2 on 2024-02-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0016_contuct_info_public_masseges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contuct_info',
            name='tip_phone_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contuct_info',
            name='tip_phone_2',
            field=models.CharField(max_length=20),
        ),
    ]
