# Generated by Django 5.0.2 on 2024-02-26 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0017_alter_contuct_info_tip_phone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_masseges',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
