# Generated by Django 5.0.2 on 2024-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0018_public_masseges_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_post_of_tip',
            name='aprove_status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='image_gallary',
            name='aprove_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
