# Generated by Django 5.0.2 on 2024-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0019_block_post_of_tip_aprove_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neerapp_coursess',
            name='disable_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
