# Generated by Django 5.0.2 on 2024-03-04 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0020_neerapp_coursess_disable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contuct_info',
            name='Create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
