# Generated by Django 5.0.2 on 2024-03-04 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0021_contuct_info_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_masseges',
            name='Create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
