# Generated by Django 5.0.2 on 2024-03-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0024_alter_notice_of_tpi_aproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_of_tpi',
            name='Expird_date',
            field=models.DateField(),
        ),
    ]
