# Generated by Django 5.0.2 on 2024-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neerapp', '0025_alter_notice_of_tpi_expird_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=15)),
                ('link_url', models.TextField()),
            ],
        ),
    ]
